### ISSUE TITLE
Can't create index with this template on Railway?

### ISSUE THREAD

**Issue by woohelps** [davlet61/meilisearch#1]
Hi There

https://docs.meilisearch.com/learn/cookbooks/railway.html
I deployed the meilisearch on railway according to above link and try to create my first index with below curl command:

https://meilisearch-production-8714.up.railway.app/

`curl \
  -X POST 'https://meilisearch-production-8714.up.railway.app/indexes/movies/documents' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer VYer03S46RuF1cpE5PnRJxrEjnZIXgnHIiFqY57zsX9A/BLU/95DUpZosYcWgOCz' \
  --data-binary @movies.json
  `
  Then It always show the status as processing of the create task:
  
 ` curl \
  -X GET 'https://meilisearch-production-8714.up.railway.app/tasks/0' \
  -H 'Authorization: Bearer VYer03S46RuF1cpE5PnRJxrEjnZIXgnHIiFqY57zsX9A/BLU/95DUpZosYcWg`
  
  Do you have any idea why would be like that? does railway support meilisearch storage?

**Comment by davlet61** [comment]
Hi 👋🏼

Railway does support meili storage.
Your app doesn't seem to be working though

<img width="1005" alt="Screenshot 2022-11-02 at 18 10 17" src="https://user-images.githubusercontent.com/30911739/199555763-e873a5a5-b01e-403f-9057-dd3b15767ee5.png">

**Comment by davlet61** [comment]
I tried to deploy and send a post request and it worked fine. Can you check your logs in Railway? 
Here is my outcome: 
- Terminal
<img width="573" alt="Screenshot 2022-11-02 at 18 34 59" src="https://user-images.githubusercontent.com/30911739/199561470-db1875b1-36fd-4944-a0e5-8e394c04852e.png">

- Meili Dashboard
<img width="1224" alt="Screenshot 2022-11-02 at 18 36 54" src="https://user-images.githubusercontent.com/30911739/199561688-dd060d71-52c6-4fbf-bf1a-22014fa64c57.png">

**Comment by woohelps** [comment]
Thanks for quick verify.  
I figured out the failure reason, because I was using the free plan(only 512 RAM) of Railway, it was out of resource when I try to upload documents.
